tls_enabled: true
grpc:
  host: qd.api.gateway
  port: 9000
email_service:
  host: qd.email.api
  port: 9091
authentication_service:
  host: qd.authentication.api
  port: 9090
visualization_service:
  host: qd.visualization.api
  port: 9092