name: Go CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    container: tavoargento/quadev-go-service:0.0.1  # Specify the Docker image
    env:
      MONGO_DB_VERSION: 4.4.28

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: go mod download

      - name: Run Go Format Check
        run: set -e; gofmt -s -l . | tee /dev/stderr

      - name: Run Go Import Check
        run: set -e; goimports -l . | tee /dev/stderr

      - name: Run Go Lint
        run: set -e; golint ./...

      - name: Add certificates
        run: |
          mkdir certs
          cd certs
          echo "${{ secrets.CA_PEM }}" | base64 -d > ca.pem
          cd -

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Build
        run: go build cmd/main.go

  build-and-push:
    needs: build
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 116203835544.dkr.ecr.eu-west-1.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build Docker image
        run: |
          docker buildx build \
          --file Dockerfile \
          --tag 116203835544.dkr.ecr.eu-west-1.amazonaws.com/test.qd-api-gateway:0.0.0 \
          --output type=image,push=true .

      - name: Cleanup
        run: |
          docker image prune -f